name: Deploy to GitHub pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.0
        with:
         dotnet-version: 5.0
         include-prerelease: true

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Publish
        run: dotnet publish ./SnakeGame/SnakeGame.Source.csproj -c Release -o release --nologo 
      
