name: .Net 5 Snake Game CI

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Snake Game Console Application
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: 5.0.100-preview.2.20176.6     
      - name: Publish
        run: dotnet publish ./SnakeGame/SnakeGame.Source.csproj -c Release -o release --nologo 
      
